service: esteemed-profile

# Configuration variables
custom:
  secrets:
    slackToken: ${file(secrets.yml):slackToken}
    slackTokenBot: ${file(secrets.yml):slackTokenBot}
    slackSigning: ${file(secrets.yml):slackSigning}
    allowedChannels: ${file(secrets.yml):allowedChannels}
    firebaseApp: ${file(secrets.yml):firebaseApp}
    travisToken: ${file(secrets.yml):travisToken}
    googleMaps: ${file(secrets.yml):googleMaps}
  ngrokTunnel:
    tunnels:
      - port: 3000

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 192
  timeout: 20
  environment:
    SLACK_TOKEN: ${self:custom.secrets.slackToken}
    SLACK_TOKEN_BOT: ${self:custom.secrets.slackTokenBot}
    SLACK_SIGNING_SECRET: ${self:custom.secrets.slackSigning}
    SLACK_CHANNELS: ${self:custom.secrets.allowedChannels}
    FIREBASE_APP: ${self:custom.secrets.firebaseApp}
    TRAVIS_TOKEN: ${self:custom.secrets.travisToken}
    GOOGLE_MAPS: ${self:custom.secrets.googleMaps}

functions:
  app:
    handler: src/web.handler
    events:
      - http:
          path: /{any+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
  - serverless-ngrok-tunnel
